# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/constraints/v7_xt_xgemac_xphy.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/constraints/v7_xt_conn_trd_noddr3.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/constraints/v7_xt_conn_bit_rev1_0.xdc

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/pcie3_x8_ip/pcie3_x8_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie3_x8_ip || ORIG_REF_NAME==pcie3_x8_ip}]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axi4lite_crossbar/axi4lite_crossbar.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi4lite_crossbar || ORIG_REF_NAME==axi4lite_crossbar}]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_async_fifo/axis_async_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_async_fifo || ORIG_REF_NAME==axis_async_fifo}]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cmd_fifo_xgemac_rxif || ORIG_REF_NAME==cmd_fifo_xgemac_rxif}]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_wr/axis_ic_wr.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_ic_wr || ORIG_REF_NAME==axis_ic_wr}]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_rd/axis_ic_rd.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_ic_rd || ORIG_REF_NAME==axis_ic_rd}]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_mac_axi_st_ip/ten_gig_eth_mac_axi_st_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ten_gig_eth_mac_axi_st_ip || ORIG_REF_NAME==ten_gig_eth_mac_axi_st_ip}]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip/ten_gig_eth_pcs_pma_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_ip || ORIG_REF_NAME==ten_gig_eth_pcs_pma_ip}]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/ten_gig_eth_pcs_pma_ip_shared_logic_in_core.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_ip_shared_logic_in_core || ORIG_REF_NAME==ten_gig_eth_pcs_pma_ip_shared_logic_in_core}]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/pcie3_x8_ip/source/pcie3_x8_ip-PCIE_X0Y1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie3_x8_ip || ORIG_REF_NAME==pcie3_x8_ip}] {/inst }]/inst ]]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/pcie3_x8_ip/synth/pcie3_x8_ip_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axi4lite_crossbar/axi4lite_crossbar_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_async_fifo/axis_async_fifo/axis_async_fifo_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_async_fifo || ORIG_REF_NAME==axis_async_fifo}] {/U0 }]/U0 ]]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_async_fifo/axis_async_fifo/axis_async_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_async_fifo || ORIG_REF_NAME==axis_async_fifo}] {/U0 }]/U0 ]]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_async_fifo/axis_async_fifo_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==cmd_fifo_xgemac_rxif || ORIG_REF_NAME==cmd_fifo_xgemac_rxif}] {/U0 }]/U0 ]]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_wr/axis_ic_wr_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_wr/axis_ic_wr_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_ic_wr || ORIG_REF_NAME==axis_ic_wr}] {/inst }]/inst ]]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_rd/axis_ic_rd_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_rd/axis_ic_rd_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_ic_rd || ORIG_REF_NAME==axis_ic_rd}] {/inst }]/inst ]]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_mac_axi_st_ip/synth/ten_gig_eth_mac_axi_st_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ten_gig_eth_mac_axi_st_ip || ORIG_REF_NAME==ten_gig_eth_mac_axi_st_ip}] {/inst }]/inst ]]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_mac_axi_st_ip/synth/ten_gig_eth_mac_axi_st_ip_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ten_gig_eth_mac_axi_st_ip || ORIG_REF_NAME==ten_gig_eth_mac_axi_st_ip}] {/inst }]/inst ]]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_mac_axi_st_ip/synth/ten_gig_eth_mac_axi_st_ip_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip/synth/ten_gig_eth_pcs_pma_ip_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_ip || ORIG_REF_NAME==ten_gig_eth_pcs_pma_ip}] {/inst }]/inst ]]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip/synth/ten_gig_eth_pcs_pma_ip_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip/synth/ten_gig_eth_pcs_pma_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_ip || ORIG_REF_NAME==ten_gig_eth_pcs_pma_ip}] {/inst }]/inst ]]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_ip_shared_logic_in_core || ORIG_REF_NAME==ten_gig_eth_pcs_pma_ip_shared_logic_in_core}] {/inst }]/inst ]]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_ip_shared_logic_in_core || ORIG_REF_NAME==ten_gig_eth_pcs_pma_ip_shared_logic_in_core}] {/inst }]/inst ]]
