# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7vx690tffg1761-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.cache/wt [current_project]
set_property parent.project_path /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/ppan/DUT/small_data_compression
  /home/ppan/Desktop/small_data_compression/small_data_compression.srcs
} [current_project]
set_property verilog_define {USE_XPHY=1 USE_PVTMON=1} [current_fileset]
add_files -quiet /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.runs/dma_back_end_axi_synth_1/dma_back_end_axi.dcp
set_property used_in_implementation false [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.runs/dma_back_end_axi_synth_1/dma_back_end_axi.dcp]
add_files -quiet /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.runs/fp_adder_synth_1/fp_adder.dcp
set_property used_in_implementation false [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.runs/fp_adder_synth_1/fp_adder.dcp]
add_files -quiet /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.runs/fp_div_synth_1/fp_div.dcp
set_property used_in_implementation false [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.runs/fp_div_synth_1/fp_div.dcp]
add_files -quiet /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.runs/fp2fixed_synth_1/fp2fixed.dcp
set_property used_in_implementation false [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.runs/fp2fixed_synth_1/fp2fixed.dcp]
add_files -quiet /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.runs/compression_synth_1/compression.dcp
set_property used_in_implementation false [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.runs/compression_synth_1/compression.dcp]
read_ip /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/pcie3_x8_ip/pcie3_x8_ip.xci
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/pcie3_x8_ip/source/pcie3_x8_ip-PCIE_X0Y1.xdc]
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/pcie3_x8_ip/synth/pcie3_x8_ip_ooc.xdc]
set_property is_locked true [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/pcie3_x8_ip/pcie3_x8_ip.xci]

read_ip /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axi4lite_crossbar/axi4lite_crossbar.xci
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axi4lite_crossbar/axi4lite_crossbar_ooc.xdc]
set_property is_locked true [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axi4lite_crossbar/axi4lite_crossbar.xci]

read_ip /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_async_fifo/axis_async_fifo.xci
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_async_fifo/axis_async_fifo/axis_async_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_async_fifo/axis_async_fifo/axis_async_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_async_fifo/axis_async_fifo_ooc.xdc]
set_property is_locked true [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_async_fifo/axis_async_fifo.xci]

read_ip /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif.xci
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif.xdc]
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif_ooc.xdc]
set_property is_locked true [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif.xci]

read_ip /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_wr/axis_ic_wr.xci
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_wr/axis_ic_wr_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_wr/axis_ic_wr_clocks.xdc]
set_property is_locked true [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_wr/axis_ic_wr.xci]

read_ip /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_rd/axis_ic_rd.xci
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_rd/axis_ic_rd_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_rd/axis_ic_rd_clocks.xdc]
set_property is_locked true [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/axis_ic_rd/axis_ic_rd.xci]

read_ip /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_mac_axi_st_ip/ten_gig_eth_mac_axi_st_ip.xci
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_mac_axi_st_ip/synth/ten_gig_eth_mac_axi_st_ip.xdc]
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_mac_axi_st_ip/synth/ten_gig_eth_mac_axi_st_ip_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_mac_axi_st_ip/synth/ten_gig_eth_mac_axi_st_ip_ooc.xdc]
set_property is_locked true [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_mac_axi_st_ip/ten_gig_eth_mac_axi_st_ip.xci]

read_ip /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip/ten_gig_eth_pcs_pma_ip.xci
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip/synth/ten_gig_eth_pcs_pma_ip_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip/synth/ten_gig_eth_pcs_pma_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip/synth/ten_gig_eth_pcs_pma_ip.xdc]
set_property is_locked true [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip/ten_gig_eth_pcs_pma_ip.xci]

read_ip /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/ten_gig_eth_pcs_pma_ip_shared_logic_in_core.xci
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/synth/ten_gig_eth_pcs_pma_ip_shared_logic_in_core.xdc]
set_property is_locked true [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_catalog/ten_gig_eth_pcs_pma_ip_shared_logic_in_core/ten_gig_eth_pcs_pma_ip_shared_logic_in_core.xci]

read_verilog -library xil_defaultlib {
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/common/axilite_system.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_cores/axi_lite_ipif/address_decoder.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_cores/axi_lite_ipif/axi_lite_ipif.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_cores/axi_lite_ipif/pselect_f.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_cores/axi_lite_ipif/counter_f.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_cores/axi_lite_ipif/slave_attachment.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/common/synchronizer_simple.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/common/synchronizer_vector.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/common/registers.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/common/user_registers_slave.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/common/pcie_monitor_gen3.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/packet_dma_axi.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/axis_ic_bram.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/network_path/rx_interface.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/network_path/network_path_shared.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/network_path/network_path.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/gen_chk/crc32_D32_wrapper.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/gen_chk/hdr_crc_checker.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/gen_chk/hdr_crc_insert.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/gen_chk/axi_stream_gen.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/gen_chk/axi_stream_crc_gen_check.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/pipe_clock.v
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/xt_connectivity_trd.v
  /home/ppan/comp/decomp.v
  /home/ppan/comp/array2axis.v
  /home/ppan/comp/dummy_decomp.v
  /home/ppan/comp/2D_array_pack_unpack.v
  /home/ppan/comp/comp.v
  /home/ppan/comp/dummy_comp.v
  /home/ppan/comp/decompression.v
  /home/ppan/real_comp/sz_1_4.v
  /home/ppan/real_comp/sz_compress_1.4.v
}
read_vhdl -library xil_defaultlib {
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/pvtmon/kcpsm6.vhd
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/pvtmon/power_test_control.vhd
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/pvtmon/vc709_power_test.vhd
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/pvtmon/power_test_control_program.vhd
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/clock_control/clock_control.vhd
  /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/hdl/clock_control/clock_control_program.vhd
}
read_xdc /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/constraints/v7_xt_xgemac_xphy.xdc
set_property used_in_implementation false [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/constraints/v7_xt_xgemac_xphy.xdc]

read_xdc /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/constraints/v7_xt_conn_trd_noddr3.xdc
set_property used_in_implementation false [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/constraints/v7_xt_conn_trd_noddr3.xdc]

read_xdc /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/constraints/v7_xt_conn_bit_rev1_0.xdc
set_property used_in_implementation false [get_files /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/constraints/v7_xt_conn_bit_rev1_0.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file xt_connectivity_trd.hwdef }
synth_design -top xt_connectivity_trd -part xc7vx690tffg1761-2 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
write_checkpoint xt_connectivity_trd.dcp
catch { report_utilization -file xt_connectivity_trd_utilization_synth.rpt -pb xt_connectivity_trd_utilization_synth.pb }
