# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7vx690tffg1761-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.cache/wt [current_project]
set_property parent.project_path /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/ppan/DUT/small_data_compression
  /home/ppan/Desktop/small_data_compression/small_data_compression.srcs
} [current_project]
set_property verilog_define {USE_XPHY=1 USE_PVTMON=1} [current_fileset]
read_verilog -library xil_defaultlib /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/ip_cores/dma/netlist/eval/dma_back_end_axi.vp
read_xdc -mode out_of_context /home/ppan/vc709/v7_xt_conn_trd/hardware/sources/constraints/dma_back_end_axi_ooc.xdc

catch { write_hwdef -file dma_back_end_axi.hwdef }
synth_design -top dma_back_end_axi -part xc7vx690tffg1761-2 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5 -mode out_of_context
rename_ref -prefix_all dma_back_end_axi_
write_checkpoint -noxdef dma_back_end_axi.dcp
catch { report_utilization -file dma_back_end_axi_utilization_synth.rpt -pb dma_back_end_axi_utilization_synth.pb }
