# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/frankqz/c35fb864-558a-4c20-ae81-7faa0c86f8e4/Xilinx/projects/small_data_compression/small_data_compression.srcs/sources_1/ip/dout_bram/dout_bram.xci
# IP: The module: 'dout_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/frankqz/c35fb864-558a-4c20-ae81-7faa0c86f8e4/Xilinx/projects/small_data_compression/small_data_compression.srcs/sources_1/ip/dout_bram/dout_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dout_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /media/frankqz/c35fb864-558a-4c20-ae81-7faa0c86f8e4/Xilinx/projects/small_data_compression/small_data_compression.srcs/sources_1/ip/dout_bram/dout_bram.xci
# IP: The module: 'dout_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/frankqz/c35fb864-558a-4c20-ae81-7faa0c86f8e4/Xilinx/projects/small_data_compression/small_data_compression.srcs/sources_1/ip/dout_bram/dout_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dout_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
