# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/fp2fixed/fp2fixed.xci
# IP: The module: 'fp2fixed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/fp2fixed/fp2fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp2fixed'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/fp2fixed/fp2fixed.xci
# IP: The module: 'fp2fixed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/fp2fixed/fp2fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp2fixed'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
