# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/compression.xci
# IP: The module: 'compression' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/sg_bram/sg_bram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sg_bram || ORIG_REF_NAME==sg_bram}]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/sg_bram_controller/sg_bram_controller.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sg_bram_controller || ORIG_REF_NAME==sg_bram_controller}]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/DMA/DMA.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA || ORIG_REF_NAME==DMA}]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/controller/controller.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller || ORIG_REF_NAME==controller}]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/dout_bram/dout_bram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dout_bram || ORIG_REF_NAME==dout_bram}]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/sg_bram/sg_bram_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/sg_bram_controller/sg_bram_controller_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/DMA/DMA_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/DMA/DMA.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DMA || ORIG_REF_NAME==DMA}] {/U0 }]/U0 ]]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/DMA/DMA_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DMA || ORIG_REF_NAME==DMA}] {/U0 }]/U0 ]]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/controller/controller_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/dout_bram/dout_bram_ooc.xdc

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/compression.xci
# IP: The module: 'compression' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/sg_bram/sg_bram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sg_bram || ORIG_REF_NAME==sg_bram}]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/sg_bram_controller/sg_bram_controller.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sg_bram_controller || ORIG_REF_NAME==sg_bram_controller}]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/DMA/DMA.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA || ORIG_REF_NAME==DMA}]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/controller/controller.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controller || ORIG_REF_NAME==controller}]

# IP: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/dout_bram/dout_bram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dout_bram || ORIG_REF_NAME==dout_bram}]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/sg_bram/sg_bram_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/sg_bram_controller/sg_bram_controller_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/DMA/DMA_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/DMA/DMA.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DMA || ORIG_REF_NAME==DMA}] {/U0 }]/U0 ]]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/DMA/DMA_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DMA || ORIG_REF_NAME==DMA}] {/U0 }]/U0 ]]

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/controller/controller_ooc.xdc

# XDC: /home/ppan/vc709/v7_xt_conn_trd/hardware/vivado/runs/xt_conn_trd.srcs/sources_1/ip/compression_4/sources_1/ip/dout_bram/dout_bram_ooc.xdc
