# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7vx690tffg1761-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ppan/Desktop/small_data_compression/small_data_compression.cache/wt [current_project]
set_property parent.project_path /home/ppan/Desktop/small_data_compression/small_data_compression.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc709:part0:1.4 [current_project]
set_property ip_repo_paths {
  /home/ppan/Desktop/small_data_compression/small_data_compression.srcs
  /home/ppan/DUT/small_data_compression
} [current_project]
add_files -quiet /home/ppan/Desktop/small_data_compression/small_data_compression.runs/dout_bram_synth_1/dout_bram.dcp
set_property used_in_implementation false [get_files /home/ppan/Desktop/small_data_compression/small_data_compression.runs/dout_bram_synth_1/dout_bram.dcp]
add_files -quiet /home/ppan/Desktop/small_data_compression/small_data_compression.runs/controller_synth_1/controller.dcp
set_property used_in_implementation false [get_files /home/ppan/Desktop/small_data_compression/small_data_compression.runs/controller_synth_1/controller.dcp]
add_files -quiet /home/ppan/Desktop/small_data_compression/small_data_compression.runs/DMA_synth_1/DMA.dcp
set_property used_in_implementation false [get_files /home/ppan/Desktop/small_data_compression/small_data_compression.runs/DMA_synth_1/DMA.dcp]
add_files -quiet /home/ppan/Desktop/small_data_compression/small_data_compression.runs/sg_bram_controller_synth_1/sg_bram_controller.dcp
set_property used_in_implementation false [get_files /home/ppan/Desktop/small_data_compression/small_data_compression.runs/sg_bram_controller_synth_1/sg_bram_controller.dcp]
add_files -quiet /home/ppan/Desktop/small_data_compression/small_data_compression.runs/sg_bram_synth_1/sg_bram.dcp
set_property used_in_implementation false [get_files /home/ppan/Desktop/small_data_compression/small_data_compression.runs/sg_bram_synth_1/sg_bram.dcp]
read_verilog -library xil_defaultlib {
  /home/ppan/Desktop/small_data_compression/small_data_compression.srcs/sources_1/new/trans.v
  /home/ppan/Desktop/small_data_compression/small_data_compression.srcs/sources_1/new/compress_unit.v
  /home/ppan/Desktop/small_data_compression/small_data_compression.srcs/sources_1/new/write_bram.v
  /home/ppan/Desktop/small_data_compression/small_data_compression.srcs/sources_1/new/shift_debug.v
  /home/ppan/Desktop/small_data_compression/small_data_compression.srcs/sources_1/new/sg_dma_command.v
  /home/ppan/Desktop/small_data_compression/small_data_compression.srcs/sources_1/new/compression_design.v
  /home/ppan/Desktop/small_data_compression/small_data_compression.srcs/sources_1/new/system_design.v
}
read_xdc /home/ppan/Desktop/small_data_compression/small_data_compression.srcs/constrs_1/new/system_design.xdc
set_property used_in_implementation false [get_files /home/ppan/Desktop/small_data_compression/small_data_compression.srcs/constrs_1/new/system_design.xdc]

catch { write_hwdef -file system_design.hwdef }
synth_design -top system_design -part xc7vx690tffg1761-2
write_checkpoint system_design.dcp
catch { report_utilization -file system_design_utilization_synth.rpt -pb system_design_utilization_synth.pb }
